### ISSUE TITLE
Vue 2 compatibility

### ISSUE THREAD

**Issue by jonalxh** [BastiaanJansen/simple-vue-camera#9]
Hi, I loved when I read the documentation on npm and wanted to use your component, but my current projects are based on Vue 2, I think that the community will apreciate if you make in compatible with this version, in my case it says `vue.defineComponent is not a function`.

Thanks a lot for your attention.

**Comment by BastiaanJansen** [comment]
Hi, Vue 2 support is currently not on my roadmap. But if you have time, contributions are welcome!

**Comment by jonalxh** [comment]
I'd like to have the time to do it, but i'm very busy, i'll keep it in mind for the future.
